name = "fediship-api-worker"
main = "src/api-worker.ts"
compatibility_date = "2022-05-19"
kv_namespaces = [
  { binding = "INSTANCE_INFO", id = "7f7cc880d83e43488f5a21515750158d", preview_id = "c46c7f6a0ee746e293bf66838930414c" },
  { binding = "KV_ERRORS", id = "f82f32aec2cb47859431f06f6a9e67ea", preview_id = "a62ffe29103a41a59607287aa5d89189" }
]

[[r2_buckets]]
binding = 'R2_ERROR_REPORTS'
bucket_name = 'fediship-error-reports'
preview_bucket_name = 'fediship-error-reports-preview'
